@url = https://olimpath-server.onrender.com

# ===========================
# 🧑‍🎓 Usuários e Autenticação
# ===========================

# Autenticação é feita pelo front end com Clerk, pegando as informações da conta google do usuário, ele é registrado no banco automaticamente

# @name registerUser
POST {{url}}/users/authenticate
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "kless123"
}

###

# @name getAllUsers
GET {{url}}/users/getAll

###

# @name getUserByEmail
GET {{url}}/users/by-email/userEmail

---

# ===========================
# 🏅 Olimpíadas
# ===========================

# @name createOlympiad
POST {{url}}/olympiads/create
Content-Type: application/json

{
  "name": "OP",
  "description": "Olimpíada de Português"
}

###

# @name getAllOlympiads
GET {{url}}/olympiads/getAll

###

# @name getOlympiadById
GET {{url}}/olympiads/getById/cmbqwhcnu00006d3uz6yba2p9

###

# @name updateOlympiad
PATCH {{url}}/olympiads/update/olympiadId
Content-Type: application/json

{
  "name": "OBQ",
  "description": "Olimpíada Brasileira de Química"
}

###

# @name deleteOlympiad
DELETE {{url}}/olympiads/delete/olympiadId

###

# @name getMaterials
GET {{url}}/olympiads/materials

###

# @name getSimulated
GET {{url}}/olympiads/olympiadId/simulated

---

# ===========================
# 🎥 Vídeos Assistidos
# ===========================
###

# @name markVideoAsWatched
POST {{url}}/users/b0c9cbd9-a134-4f00-894f-9bedd8e1772a/videos/cmcgph2pi0003w5mwxm0hrica/view

###

# @name getWatchedStatus
GET {{url}}/users/userId/videos/videoId/view

###

# @name getRecentWatched
GET {{url}}/users/userId/recent-watched

###

# @name getWatchedFromOlympiad
GET {{url}}/users/user_2yVo2pWDsTHnQItSCj3KjiScIdd/olympiads/cmbqwiasm00026d3uioa90dwr/watched

---

# ===========================
# 🤖 Chat com IA
# ===========================
###

# @name createChat
POST {{url}}/chat/create
Content-Type: application/json

{
  "userId": "user_2yPvMLzeqFLB8uQc69XcRiiql60"
}

###

# @name getChatsByUser
GET {{url}}/chats/b0c9cbd9-a134-4f00-894f-9bedd8e1772a

###

# @name getChatById
GET {{url}}/chat/chatId

###

# @name addMessageToChat
POST {{url}}/chat/chatId/message
Content-Type: application/json

{
  "sender": "USER or AI",
  "content": "Qual é a fórmula da água?"
}

###

# @name deleteChat
DELETE {{url}}/chat/delete/cmcsdbjos0000w5i47dq5qr4y

# ===========================
# 📅 Quiz Diário
# ===========================

###

# @name getTodayQuiz
GET http://localhost:3333/quiz/today

---

# ===========================
# 🏅 Gamification
# ===========================

###

GET {{url}}/gamification/ranking

###

POST {{url}}/gamification/users/userId/simulated/score
Content-Type: application/json

{
  "correctAnswers": 10,
  "totalQuestions": 20
}

###

GET {{url}}/gamification/users/userId/quiz/score