@url = https://olimpath-server.onrender.com

# ===========================
# 🧑‍🎓 Usuários e Autenticação
# ===========================

# Autenticação é feita pelo front end com Clerk, pegando as informações da conta google do usuário, ele é registrado no banco automaticamente

# @name registerUser
POST {{url}}/users/register
Content-Type: application/json

{
  "name": "Nome",
  "email": "email@email.com"
}

###

# @name getAllUsers
GET {{url}}/users/getAll

###

# @name getUserByEmail
GET {{url}}/users/by-email/userEmail

---

# ===========================
# 🏅 Olimpíadas
# ===========================

# @name createOlympiad
POST {{url}}/olympiads/create
Content-Type: application/json

{
  "name": "OP",
  "description": "Olimpíada de Português"
}

###

# @name getAllOlympiads
GET {{url}}/olympiads/getAll

###

# @name getOlympiadById
GET {{url}}/olympiads/getById/olympiadId

###

# @name updateOlympiad
PATCH {{url}}/olympiads/update/olympiadId
Content-Type: application/json

{
  "name": "OBQ",
  "description": "Olimpíada Brasileira de Química"
}

###

# @name deleteOlympiad
DELETE {{url}}/olympiads/delete/olympiadId

###

# @name getMaterials
GET {{url}}/olympiads/materials

###

# @name getSimulated
GET {{url}}/olympiads/olympiadId/simulated

---

# ===========================
# 🎥 Vídeos Assistidos
# ===========================

# @name markVideoAsWatched
POST {{url}}/users/userId/videos/videoId/view

###

# @name getWatchedStatus
GET {{url}}/users/userId/videos/videoId/view

###

# @name getRecentWatched
GET {{url}}/users/userId/recent-watched

###

# @name getWatchedFromOlympiad
GET {{url}}/users/userId/olympiads/olympiadId/watched

---

# ===========================
# 🤖 Chat com IA
# ===========================

# @name createChat
POST {{url}}/chat/create
Content-Type: application/json

{
  "userId": "user_2yPvMLzeqFLB8uQc69XcRiiql60"
}

###

# @name getChatsByUser
GET {{url}}/chats/userId

###

# @name getChatById
GET {{url}}/chat/chatId

###

# @name addMessageToChat
POST {{url}}/chat/chatId/message
Content-Type: application/json

{
  "sender": "USER or AI",
  "content": "Qual é a fórmula da água?"
}

###

# @name deleteChat
DELETE {{url}}/chat/delete/chatId

---

# ===========================
# 📅 Quiz Diário
# ===========================

###

# @name getTodayQuiz
GET {{url}}/quiz/today
