@local = http://localhost:3333
@url = https://olimpath-server.onrender.com
@token = {{authenticate.response.body.token}}

# @name authenticate
GET {{url}}/auth/google
Content-Type: application/json

###

POST {{url}}/users/register
Content-Type: application/json

{
    "name": "Klevisson Weskley",
    "email": "klevissonweskley13@gmail.com"
}

###

GET {{local}}/users/getAll
Content-Type: application/json

###

POST {{url}}/olympiads/create
Content-Type: application/json

{
    "name": "OP",
    "description": "Olimpíada de Português"
}

###

GET {{url}}/olympiads/getAll
Content-Type: application/json

###

GET {{url}}/olympiads/getById/cmbo1qyvw0001w56w2kwqsa1r
Content-Type: application/json


###

PATCH {{url}}/olympiads/update/cmajzjaur0000w5a0bg30eari
Content-Type: application/json

{
    "name": "OBQ",
    "description": "Olimpíada Brasileira de Química"
}

###

POST {{local}}/users/user_2yPvMLzeqFLB8uQc69XcRiiql60/videos/cmbo22u5y00efw5owyr9i0q05/view

###

GET {{local}}/users/user_2yPvMLzeqFLB8uQc69XcRiiql60/videos/cmbo22s1c0003w5owfoszgi9b/view

###

GET {{local}}/users/cmbqs36gr0000w5rce78rg8n0/recent-watched

###

GET {{local}}/users/by-email/klevissonweskley13@gmail.com

###

GET {{local}}/users/user_2yPvMLzeqFLB8uQc69XcRiiql60/olympiads/cmbo1o5g80000w56w89xv7syb/watched

###

GET {{local}}/olympiads/materials

###

POST {{url}}/chat/create
Content-Type: application/json

{
    "userId": "user_2yPvMLzeqFLB8uQc69XcRiiql60"
}